# .github/workflows/premerge.yml
---
name: premerge

on:
  pull_request:
    branches:
      - main

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install go-licenses
        run: go install github.com/google/go-licenses/v2@latest

      - name: Run make test
        run: make test

      - name: Run make licenses
        run: make licenses
